param(
  [Parameter(Mandatory = $true)][string]$TokenFile,
  [Parameter(Mandatory = $true)][string]$OutputFile
)

$ErrorActionPreference = 'Stop'
$tokens = [ordered]@{}

if (Test-Path -LiteralPath $TokenFile) {
  foreach ($rawLine in Get-Content -LiteralPath $TokenFile) {
    $line = $rawLine.Trim()
    if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith('#')) { continue }

    $separator = $line.IndexOf('=')
    if ($separator -lt 0) { continue }

    $server = $line.Substring(0, $separator).Trim().TrimEnd('/').ToLowerInvariant()
    $token = $line.Substring($separator + 1).Trim()
    if ([string]::IsNullOrWhiteSpace($server) -or [string]::IsNullOrWhiteSpace($token)) { continue }

    $uri = $null
    if (-not [Uri]::TryCreate($server, [UriKind]::Absolute, [ref]$uri) -or
        ($uri.Scheme -ne 'http' -and $uri.Scheme -ne 'https')) {
      continue
    }

    $tokens[$server] = $token
  }
}

function Escape-CSharp([string]$value) {
  return $value.Replace('\', '\\').Replace('"', '\"')
}

$entries = foreach ($entry in $tokens.GetEnumerator()) {
  '        ["{0}"] = "{1}"' -f (Escape-CSharp $entry.Key), (Escape-CSharp $entry.Value)
}
$initializer = if ($entries) { ($entries -join ",`n") + ',' } else { '' }

$content = @"
// <auto-generated /> Do not edit. Generated from the local token.txt during build.
using System.Collections.Generic;

namespace CvatDuplicateChecker;

internal static class GeneratedDefaultCvatTokens
{
    internal static IReadOnlyDictionary<string, string> Values { get; } =
        new Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase)
        {
$initializer
        };
}
"@

$outputDirectory = Split-Path -Parent $OutputFile
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
[IO.File]::WriteAllText($OutputFile, $content, [Text.UTF8Encoding]::new($false))
Write-Host ("Generated {0} default CVAT token entries." -f $tokens.Count)
